title: Mussiro Investments
email: info@mussiroinvestments.com
description: >- # this means to ignore newlines until "baseurl:"
  A Escolha Perfeita
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-target-blank
  - jekyll-email-protect
  - jekyll-analytics
  - jekyll-seo-tag

sass:
  sass_dir: assets/_sass
  style: compressed

logo: /assets/img/logo.svg
image: /assets/img/mussiroinvestments.svg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
